/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.adventofcode;

import java.util.Collection;
import java.util.Comparator;
import java.util.TreeSet;
import java.util.stream.Collectors;

import org.reflections.Reflections;
import org.reflections.scanners.SubTypesScanner;

import com.adventofcode.calendar.Puzzle;

public class App {

    public static void main(String[] args) {
        try {

            Collection<Class<? extends Puzzle>> puzzles = new App().getPuzzles();
            for (Class<? extends Puzzle> clazz : puzzles) {
                Puzzle puzzle = clazz.getDeclaredConstructor().newInstance();
                puzzle.run();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    public Collection<Class<? extends Puzzle>> getPuzzles() {
        Reflections reflections = new Reflections(Puzzle.class.getPackageName(), new SubTypesScanner(false));
        return reflections.getSubTypesOf(Puzzle.class)
                .stream()
                .collect(Collectors.toCollection(
                    () -> new TreeSet<>(Comparator.comparing(Class::getName))
                ));
    }
}
