/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.adventofcode;

import com.adventofcode.calendar.impl.Day1;
import com.adventofcode.calendar.impl.Day2;

public class App {

    public static void main(String[] args) {
        new Day1().run();
        new Day2().run();
    }
}
